### ISSUE TITLE
Example file

### ISSUE THREAD

**Issue by Doweig** [qoncrete/client-sdk-node#1]
An example file would be nice, like the one you did for the front end sdk

https://github.com/qoncrete/client-sdk-js/blob/master/example.html

**Comment by Pawda** [comment]
@Doweig The name is misleading, but there is something similar here:
https://github.com/qoncrete/client-sdk-node/blob/master/test.js

Edit: This file has been renamed into example.js. Soon we will change the readme.md.
Thanks for noticing!
